### ISSUE TITLE
Battery charge wrong when force charging

### ISSUE THREAD

**Issue by welshdave** [StealthChesnut/HA-FoxESS-Modbus#14]
When force charging I'm getting inflated values for battery charge. I only have a 7.8kWh battery, and checking with my meter data confirms that I didn't use anywhere near this much electricity from the grid.

![image](https://user-images.githubusercontent.com/13338/167389686-ced412f4-d2be-46d9-bdb5-652aee1e87f0.png)

**Comment by williamjeccles** [comment]
@welshdave could you show a chart of the Battery_Charge_Daily for the timespan of the issue above?

**Comment by welshdave** [comment]
This is battery charge daily:

![image](https://user-images.githubusercontent.com/13338/167465527-d55906cd-e0b2-48bb-bbe1-62927b3f457c.png)


It doesn't seem to marry up with the data from sensor.battery_charge:

![image](https://user-images.githubusercontent.com/13338/167464911-d5c89195-5e2f-4520-88a3-3894687cd281.png)

**Comment by Daibutt** [comment]
@williamjeccles I see the same with battery discharge
![image](https://user-images.githubusercontent.com/69276073/167466054-88a8763f-4343-4a48-a431-f965bc43183c.png)
That 6kWh jump was when I put a 3kW kettle on for 3 minutes! Work that out lol.
I think it may possibly be down to the way the templates work for feedin/grid consumption and bat charge/discharge. The logic sets them to **exactly zero**, sometimes for many hours, which seems to be messing with the integration sensors?
Most "normal" sensors have a bit of noise on them so we don't see this effect usually.
See my comment on this closed out issue, where I have created a random noise sensor to use instead of exactly zero.
https://github.com/StealthChesnut/HA-FoxESS-Modbus/issues/15#issuecomment-1121151086

Still early days but I haven't seen a similar jump since. Will keep monitoring.

**Comment by welshdave** [comment]
@Daibutt Interesting, I'll give that a go and see what it does.

**Comment by Daibutt** [comment]
> @Daibutt Interesting, I'll give that a go and see what it does.

Great, I'm interested to see if that works for you. Only had mine running for 12hrs or so but still looking OK so far.

**Comment by welshdave** [comment]
Looking a lot better this morning:

![image](https://user-images.githubusercontent.com/13338/167560772-a082e173-0911-4bdb-8193-7acd4ad78d2d.png)

**Comment by Captain0Kangaroo** [comment]
I didn't charge last night (although I wish I did as I'm now pulling from the gird 🙄)

However I'm seeing a big spike in my battery charge figure which is incorrect.

Dave - did your solution fix this?

![image](https://user-images.githubusercontent.com/96144685/167582602-5bd0e5d3-36d1-4d54-9d4f-80d195da4ad6.png)

**Comment by Daibutt** [comment]
@Captain0Kangaroo Mine looks good so far, no big spikes in charge/discharge or feeedin/consumption

**Comment by Captain0Kangaroo** [comment]
> @Captain0Kangaroo Mine looks good so far, no big spikes in charge/discharge or feeedin/consumption
> 
> ![image](https://user-images.githubusercontent.com/69276073/167586358-88983322-3696-4f13-9979-13653c5cc1de.png)

Could you paste your code please. I've tried to copy it but doesn't paste well and when i typed it in i think i've got a mistake somewhere as when doing a Check Configuration it throws back lots of errors.

Thanks

**Comment by Daibutt** [comment]
OK... add this in your sensor part of configuration.yaml (mine is just below the integration sensors for bat discharge, grid consumption etc.).;

```
- platform: random
  name: random_watts
  minimum: 1
  maximum: 10
```

Then find your template for battery charge
![image](https://user-images.githubusercontent.com/69276073/167597522-d65b54b3-d2c1-4aec-8d2f-75347a8b7e00.png)

and replace the zero indicated with this code;

`{{ (states('sensor.random_watts') | float - 5.5 ) / 1000 }}`

first curly bracket needs to line up with the others in the template so it looks like this;

![image](https://user-images.githubusercontent.com/69276073/167598229-1c9515cb-2354-4706-a07e-a9c44e370cb2.png)

**Comment by welshdave** [comment]
@Captain0Kangaroo - the changes @Daibutt suggested worked to stop spikes for me last night, I'll be keeping an eye on it for the next few days now.

**Comment by Captain0Kangaroo** [comment]
> OK... add this in your sensor part of configuration.yaml

Nice one - Thank you...

**Comment by Captain0Kangaroo** [comment]
Not sure what's happening now but my battery discharge and feedin are the same figure and change exactly with each other.

![image](https://user-images.githubusercontent.com/96144685/167694304-3c785f34-1fda-4325-8113-734dbe9567cb.jpeg)

**Comment by williamjeccles** [comment]
@Daibutt I think using the sum vs daily for the energy meters will solve this, doesn't it?

**Comment by williamjeccles** [comment]
correction, I see the same issue with sum. going to monitor and if still an issue try your solution.

**Comment by StealthChesnut** [comment]
I'm looking into an alternative method by adding "method: left" to the Integration sensors. The documentation for them shows the default method to be Trapezoidal, and recommend Left for "spiky" loads. I suspect it won't work though.

@Daibutt is right in that if the value is just 0 for 12 hours, then goes to 2kW, the two data points are 0 and 2, so it'll then try to average that out coming in at (very rough guess) 2ish kWh instead of 0.

I think this would likely work just as well if we had alternating 0.0001W and -0.0001W fed into the integrations every minute or so that at any point they're only integrating over 60s or less, and not time gaps of hours. It's not the fact it's random noise being put in, it's just getting Home Assistant to log additional data points more frequently, therefore shortening the time that the integration is averaging values for.

Easy version: in the wikipedia article (https://en.wikipedia.org/wiki/Riemann_sum) graphics, our bars are too wide. If we use Daibutt's method we make the bars much narrower, making the averaging much higher resolution.

**Comment by Daibutt** [comment]
Agree, alternating +1W - 1W would do it too as long as the integration
sensor sees something changing.
I just used the random sensor as it was an easy way to generate a
constantly changing number.

**Comment by StealthChesnut** [comment]
Since adding method: left to my integration definitions on the evening of the 10th I've seen less jumps, and also lower reported usage (this is bat_charge_daily):
![image](https://user-images.githubusercontent.com/46853524/168250061-655e47ff-3e0a-478b-8566-4d3e4e47ee37.png)

Are you still having success @Daibutt ? I am thinking I will add the method: left property, but also put in your random noise sensor commented out so that people can use it easily if they wish?

**Comment by Daibutt** [comment]
@StealthChesnut Yes Chris,  the random noise sensor is still working well for me. 
![image](https://user-images.githubusercontent.com/69276073/168254709-ae062142-4848-4487-90cf-6093e44d4d6a.png)


Glad you got the method:left bit to work. I thought I'd tried that at some point and it didn't fix the issue, but maybe I tried right and did't get round to left !

Yes, if you don't think it will cause confusion, by all means include the random noise stuff commented out.

**Comment by StealthChesnut** [comment]
Added method: left to integration sensors, closing this issue. Will add a noise sensor as option.
